apiVersion: apps/v1
kind: Deployment
metadata:
  name: ioi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ioi
  template:
    metadata:
      labels:
        app: ioi
    spec:
      containers:
      - image: okteto.dev/ioi:latest
        name: ioi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "971eb037-b4d9-4497-b30e-98a341f164db"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "971eb037-b4d9-4497-b30e-98a341f164db"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
