apiVersion: apps/v1
kind: Deployment
metadata:
  name: fff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fff
  template:
    metadata:
      labels:
        app: fff
    spec:
      containers:
      - image: okteto.dev/fff:latest
        name: fff
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "89c40ac3-a9da-4b9b-ae9e-2410d14f2644"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "89c40ac3-a9da-4b9b-ae9e-2410d14f2644"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
