apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmm
  template:
    metadata:
      labels:
        app: mmm
    spec:
      containers:
      - image: okteto.dev/mmm:latest
        name: mmm
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "1fb0b79c-3717-44cd-ac5e-e7946e92201e"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "1fb0b79c-3717-44cd-ac5e-e7946e92201e"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
