apiVersion: apps/v1
kind: Deployment
metadata:
  name: zzz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zzz
  template:
    metadata:
      labels:
        app: zzz
    spec:
      containers:
      - image: okteto.dev/zzz:latest
        name: zzz
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "c35a94a7-079a-4fb2-808c-9887f02f64fd"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "c35a94a7-079a-4fb2-808c-9887f02f64fd"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
